### ISSUE TITLE
Question about cmd

### ISSUE THREAD

**Issue by unameddev** [wnetMC/Windows-Defender-Bypass#1]
Hey wnetMC, thanks for the fork! I have a question, theres some way to make the cmd window run in the background or minimized? for the project im working on, the user cant see the window or whats happening... I await your reply

best regards.

**Comment by slezercc** [comment]
Hey, you could download bat to exe converter and make it run in a minimized console. That would be the easiest way.

**Comment by FCount** [comment]
Thanks for everything so far. In my case you're making that mistake. Can you help me? https://ibb.co/SKRHrV7

**Comment by unameddev** [comment]
> Thanks for everything so far. In my case you're making that mistake. Can you help me? https://ibb.co/SKRHrV7 

Percebi que você é br... me manda uma mensagem no telegram, posso te ajudar. https://t.me/x02r88

**Comment by slezercc** [comment]
> Thanks for everything so far. In my case you're making that mistake. Can you help me? https://ibb.co/SKRHrV7

![image](https://user-images.githubusercontent.com/37955902/210691305-26cb676f-feaf-4d26-a47f-d68348458716.png)
this does not seem right, did you create an html and css replit? the url should look like this: https://replitname.replitusername.repl.co/installer.bat

**Comment by unameddev** [comment]
@wnetMC We got it working MC! So, we've been running some tests lately and i've come across 2 things... First, the bat to exe converter dont minimize the cmd window, i've got it working for the first window tho but the next 2 keep poping up. Second, can we do this bypass without having the UAC Screen poping up too? 
I hope you can help us with this, thanks!

**Comment by slezercc** [comment]
@unameddev Im not sure if it's possible to bypass the uac screen, and you would have to convert all the batchfiles to exe with the hidden window option on all of them for it to be invisible.
