### ISSUE TITLE
Help with Replit - PLEASE

### ISSUE THREAD

**Issue by JellyAnchovies** [wnetMC/Windows-Defender-Bypass#5]
I cant seem to get my web server to host the file with the proper link format, I'm having the same issue as 
https://github.com/slezercc/antivirus-bypass/issues/1#issuecomment-1371722340

**Comment by JellyAnchovies** [comment]
My links are formatted like his replit.com/(user)/(sitename)

**Comment by slezercc** [comment]
Did you create a PHP Web Server repl?

**Comment by JellyAnchovies** [comment]
No I made a HTML, CSS & JS repl like it says in the README

**Comment by slezercc** [comment]
okay well this works too, once you created the replit, you need to upload your bat file in the files section on the left (where index.html, style,css and script,js is showing.) and then press the green run button at the top of your replit, after that, a window previewing your website should popup, with your website's url on top.
